DATA SEGMENT
    NUM1 DW 30H
    NUM2 DW 60H
    GCD DW ?
DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE DS:DATA
START:MOV AX,DATA
      MOV DS,AX
      MOV BX,1100H
      MOV DI,1200H
      MOV AX,NUM1
      MOV CX,NUM2
BACK: CMP AX,CX
      JE STORE
      JNC NEXT
      XCHG AX,CX
NEXT: MOV DX,0000H
      DIV CX
      CMP DX,0000H
      JE STORE
      MOV AX,DX
      JMP BACK
STORE:MOV GCD,CX
      INT 21H
CODE ENDS
END START