DATA SEGMENT
    STR DB "SIES GST NERUL$"
    LENGTH DB ?
DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE DS:DATA
START:MOV AX,DATA
      MOV DS,AX
      MOV SI,OFFSET STR
      MOV AL,'$'
      MOV CL,00H
BACK: CMP AL,[SI]
      JE LAST
      INC SI
      INC CL
      JMP BACK
LAST: MOV LENGTH,CL
      MOV AH,4CH
      INT 21H
CODE ENDS
END START